<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX44SRDr\Glpi_Kernel_KernelProductionContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX44SRDr/Glpi_Kernel_KernelProductionContainer.php') {
    touch(__DIR__.'/ContainerX44SRDr.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionContainer::class, false)) {
    \class_alias(\ContainerX44SRDr\Glpi_Kernel_KernelProductionContainer::class, Glpi_Kernel_KernelProductionContainer::class, false);
}

return new \ContainerX44SRDr\Glpi_Kernel_KernelProductionContainer([
    'container.build_hash' => 'X44SRDr',
    'container.build_id' => 'aaffd04a',
    'container.build_time' => 1759415874,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX44SRDr');
